# See style guide: https://github.com/airbnb/javascript
extends: airbnb
parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
# Override a couple of rules because no style guide is perfect.
rules:
    comma-dangle: [error, never]
    # PEP8 uses 4 spaces, it's just easier this way.
    indent: [error, 4]
    react/jsx-indent: [error, 4]
    react/jsx-indent-props: [error, 4]
    # There are edge cases such as (x) => { foo: [] } which are syntactically
    # ambiguous, does it return an object or is that a labeled block?
    arrow-body-style: [off, always]
    # Immutable.js breaks linting without this rule
    # usage will require import { Map as ImmutableMap, List as ImmutableList }
    # as allowing just Map will also exempt the built-in JS Map object
    new-cap:
      - 1
      - capIsNewExceptions: [ImmutableList, ImmutableMap]
